trigger:
- main  

pool:
  name: 'QA_Backend_Automation'
  vmImage: 'latest'

steps:
- script: |
    python3 -m pip install --upgrade pip setuptools
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python3 -m pytest --junitxml=tests/test-results.xml --cov=. --cov-report=xml --cov-report=html
  displayName: 'Run pytest'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'tests/test-*.xml'
  condition: succeededOrFailed()
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  condition: succeededOrFailed()
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)htmlcov'
  condition: succeededOrFailed()
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(System.DefaultWorkingDirectory)
    artifactName: MyBuildOutputs
- task: BuildQualityChecks@6
  displayName: 'Check build quality'
  inputs:
    coverageType: lines
    checkCoverage: true
    coverageFailOption: fixed
    coverageThreshold: 70
